name: |
  MyName

description: |
  MyDescription

artist: MyArtist
genre: Podcast
artwork: MyArtwork.jpg
media_uri: http://my.media/uri  # Include protocol. Omit trailing slash.

uploads:
- name: MyName
  host: MyHost.com
  path: My/Path
  user: MyUser
  pass: MyPassword

views:
- name: MyView
  template: MyTemplateFile

email:
- subject: |
    MySubject

  recipients:
  - him@here.com
  - her@there.com

  recipient_salutation: TheirName
  from: me@from.com
  from_salutation: MyName
  template: MyEmailTemplateFile


slack:
- url: https://hooks.slack.com/services/SET/THIS
  username: Andy
  channel: "@andy"
  template: MySlackTemplateFile

