name: Underpants
artist: Ned Kelly
description: MyDescription
artwork: MyArtwork.jpg
media_uri: My.Media/URI/

uploads:
  - 
    name: MyName
    host: MyHost.com
    path: My/Path
    user: MyUser
    pass: MyPassword
    
views:
  -
    name: MyName
    template: MyTemplateFile
    
informs:
  -
    subject: MySubject
    
    recipients:
      - him@here.com
      - her@there.com
    
    from: My@From
    template: MyTemplateFile
