name: |
  MyName

description: |
  MyDescription

artist: MyArtist
genre: Podcast
artwork: MyArtwork.jpg
media_uri: My.Media/URI/

uploads:
- name: MyName
  host: MyHost.com
  path: My/Path
  user: MyUser
  pass: MyPassword

views:
- name: MyView
  template: MyTemplateFile

informs:
- subject: |
    MySubject

  recipients:
  - him@here.com
  - her@there.com

  from: me@from.com
  template: MyInformTemplateFile

